### ISSUE TITLE
response from mssql 

### ISSUE THREAD

**Issue by starley00** [Tw1sm/PySQLRecon#5]
When you implement attacks on the mssql server, there is no response or output.
![1](https://github.com/Tw1sm/PySQLRecon/assets/100708808/2dd87d8f-e14e-403f-9c86-50f4d1feae3b)
![2](https://github.com/Tw1sm/PySQLRecon/assets/100708808/a2172f4e-483b-44dd-adf8-97d03a5f2f31)
![3](https://github.com/Tw1sm/PySQLRecon/assets/100708808/3f46d05a-0f8d-4ec6-b9ef-e6532e52153e)
![4](https://github.com/Tw1sm/PySQLRecon/assets/100708808/1db64ffa-8227-4933-aba7-490b1c7892cc)

**Comment by Tw1sm** [comment]
This is expected behavior. The warning `No results found` does not indicate your query has failed, it indicates your SQL statement/query did not produce output with columns/rows, which your screenshots confirm.

Additionally, you are misusing single quotes in your procedure creation - use outer double quotes.
